version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "dantech2000"
    assignees:
      - "dantech2000"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    # Auto-merge patch and minor updates for Go modules
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"  
        update-type: "version-update:semver-minor"
      - dependency-type: "indirect"
        update-type: "version-update:semver-patch"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "github.com/aws/aws-sdk-go-v2/*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "dantech2000"
    assignees:
      - "dantech2000"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions" 