# GoReleaser config for the 'refresh' CLI tool
# See https://goreleaser.com/customization/ for full docs

version: 2

dist: dist

env:
  - GITHUB_TOKEN={{ .Env.GH_PAT }}

builds:
  - id: refresh
    main: ./main.go
    binary: refresh
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/dantech2000/refresh/internal/commands.version={{.Version}}
      - -X github.com/dantech2000/refresh/internal/commands.commit={{.ShortCommit}}
      - -X github.com/dantech2000/refresh/internal/commands.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: refresh
    repository:
      owner: dantech2000
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GH_PAT }}"
    directory: Formula
    homepage: "https://github.com/dantech2000/refresh"
    description: "Manage and monitor AWS EKS node groups using your local kubeconfig and AWS credentials"
    license: "MIT"
    test: |
      system "#{bin}/refresh version"
    install: |
      bin.install "refresh"

release:
  github:
    owner: dantech2000
    name: refresh
