package commands

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/urfave/cli/v3"
)

// GenDocsCommand returns a hidden command that generates the Markdown command
// reference for the docs site directly from the live CLI tree. Because it walks
// the same *cli.Command tree the binary runs, the reference can never drift from
// the actual flags. Run it via `task docs:gen`. (REF-108)
func GenDocsCommand() *cli.Command {
	return &cli.Command{
		Name:   "gen-docs",
		Hidden: true,
		Usage:  "Generate the Markdown command reference from the CLI tree",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "out",
				Usage: "Output directory for the generated reference",
				Value: "docs/reference",
			},
		},
		Action: runGenDocs,
	}
}

// genDocFileMode/genDocDirMode are the permissions for generated files/dirs.
const (
	genDocFileMode = 0o644
	genDocDirMode  = 0o755
)

func runGenDocs(_ context.Context, cmd *cli.Command) error {
	root := cmd.Root()
	outDir := cmd.String("out")
	if err := os.MkdirAll(outDir, genDocDirMode); err != nil {
		return fmt.Errorf("creating %s: %w", outDir, err)
	}

	top := visibleSubcommands(root)

	// One page per top-level command, plus an index with the global flags.
	if err := writeFile(filepath.Join(outDir, "index.md"), renderIndex(root, top)); err != nil {
		return err
	}
	for _, c := range top {
		page := renderCommandPage(c, "refresh")
		if err := writeFile(filepath.Join(outDir, c.Name+".md"), page); err != nil {
			return err
		}
	}

	fmt.Printf("Generated %d reference pages in %s\n", len(top)+1, outDir)
	return nil
}

// generatedNote marks a file as machine-generated so nobody hand-edits it.
const generatedNote = "<!-- Generated by `refresh gen-docs` — do not edit. Run `task docs:gen`. -->\n\n"

func renderIndex(root *cli.Command, top []*cli.Command) string {
	var b strings.Builder
	b.WriteString(generatedNote)
	b.WriteString("# Command reference\n\n")
	b.WriteString("Complete, auto-generated reference for every `refresh` command and flag. ")
	b.WriteString("It is generated from the CLI definition, so it always matches the binary.\n\n")

	b.WriteString("## Commands\n\n")
	b.WriteString("| Command | Description |\n|---|---|\n")
	for _, c := range top {
		fmt.Fprintf(&b, "| [`refresh %s`](%s.md) | %s |\n", c.Name, c.Name, escapeCell(c.Usage))
	}
	b.WriteString("\n")

	if flags := visibleFlags(root.Flags); len(flags) > 0 {
		b.WriteString("## Global flags\n\n")
		b.WriteString("These are accepted on every command.\n\n")
		b.WriteString(renderFlagTable(flags))
	}
	return b.String()
}

func renderCommandPage(c *cli.Command, parentPath string) string {
	var b strings.Builder
	b.WriteString(generatedNote)
	b.WriteString("# refresh " + c.Name + "\n\n")
	renderCommandBody(&b, c, parentPath, 2)
	return b.String()
}

// renderCommandBody renders a command's usage/description/flags and recurses
// into its subcommands at the given heading level.
func renderCommandBody(b *strings.Builder, c *cli.Command, parentPath string, level int) {
	path := strings.TrimSpace(parentPath + " " + c.Name)

	if c.Usage != "" {
		b.WriteString("> " + c.Usage + "\n\n")
	}
	if len(c.Aliases) > 0 {
		b.WriteString("**Aliases:** " + codeList(c.Aliases) + "\n\n")
	}

	// Synopsis
	syn := path
	if len(visibleFlags(c.Flags)) > 0 {
		syn += " [options]"
	}
	if c.ArgsUsage != "" {
		syn += " " + c.ArgsUsage
	} else if len(visibleSubcommands(c)) > 0 {
		syn += " <command>"
	}
	b.WriteString("```\n" + syn + "\n```\n\n")

	if d := strings.TrimSpace(c.Description); d != "" {
		b.WriteString(d + "\n\n")
	}

	if flags := visibleFlags(c.Flags); len(flags) > 0 {
		b.WriteString(heading(level, "Flags"))
		b.WriteString(renderFlagTable(flags))
	}

	subs := visibleSubcommands(c)
	if len(subs) > 0 {
		b.WriteString(heading(level, "Subcommands"))
		for _, sc := range subs {
			b.WriteString(heading(level+1, "refresh "+path[len("refresh "):]+" "+sc.Name))
			renderCommandBody(b, sc, path, level+2)
		}
	}
}

func renderFlagTable(flags []cli.Flag) string {
	var b strings.Builder
	b.WriteString("| Flag | Env | Default | Description |\n|---|---|---|---|\n")
	for _, f := range flags {
		df, ok := f.(cli.DocGenerationFlag)
		if !ok {
			continue
		}
		name := flagNames(f, df)
		env := "—"
		if vars := df.GetEnvVars(); len(vars) > 0 {
			env = codeList(vars)
		}
		def := defaultText(df)
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
			name, env, def, escapeCell(df.GetUsage()))
	}
	b.WriteString("\n")
	return b.String()
}

// defaultText renders a flag's default for the table. The flags aren't applied
// to a flag set during doc generation, so GetDefaultText() is empty — the value
// representation (GetValue) carries the default instead. Strings come back
// quoted; zero-values (empty/0/false) are suppressed as noise.
func defaultText(df cli.DocGenerationFlag) string {
	if !df.TakesValue() {
		return "—"
	}
	v := df.GetDefaultText()
	if v == "" {
		v = strings.Trim(df.GetValue(), `"`)
	}
	switch v {
	case "", "0", "false", "0s", "[]":
		return "—"
	}
	return "`" + v + "`"
}

// flagNames renders a flag's names as `--long, -a <type>`.
func flagNames(f cli.Flag, df cli.DocGenerationFlag) string {
	names := append([]string(nil), f.Names()...)
	// Longest name is the canonical long form; shorter ones are aliases.
	sort.SliceStable(names, func(i, j int) bool { return len(names[i]) > len(names[j]) })
	parts := make([]string, 0, len(names))
	for _, n := range names {
		if len(n) == 1 {
			parts = append(parts, "-"+n)
		} else {
			parts = append(parts, "--"+n)
		}
	}
	out := "`" + strings.Join(parts, ", ")
	if df.TakesValue() {
		if t := df.TypeName(); t != "" {
			out += " " + t
		}
	}
	return out + "`"
}

func visibleSubcommands(c *cli.Command) []*cli.Command {
	var out []*cli.Command
	for _, sc := range c.Commands {
		// Skip hidden commands and the framework-added `help` command.
		if sc.Hidden || sc.Name == "help" {
			continue
		}
		out = append(out, sc)
	}
	return out
}

func visibleFlags(flags []cli.Flag) []cli.Flag {
	var out []cli.Flag
	for _, f := range flags {
		if bf, ok := f.(*cli.BoolFlag); ok && bf.Hidden {
			continue
		}
		out = append(out, f)
	}
	return out
}

func heading(level int, text string) string {
	return strings.Repeat("#", level) + " " + text + "\n\n"
}

func codeList(items []string) string {
	parts := make([]string, len(items))
	for i, s := range items {
		parts[i] = "`" + s + "`"
	}
	return strings.Join(parts, ", ")
}

// escapeCell makes a string safe for a Markdown table cell.
func escapeCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.TrimSpace(s)
}

func writeFile(path, content string) error {
	if err := os.WriteFile(path, []byte(content), genDocFileMode); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}
